### ISSUE TITLE
"can't concat bytes to str"

### ISSUE THREAD

**Issue by kevnk** [fitnr/SublimeCSSTidy#22]
SBT3 on Yosemite; Running `Tidy CSS` opens an empty file and displays this in the sublime console:

```
CSSTidy: tidying /www/path/to/loading.css with args: {}
CSSTidy: Sending command:php -f /Users/kevinkirchner/Library/Application Support/Sublime Text 3/Packages/CSSTidy/csstidy.php --
CSSTidy returned 1
CSSTidy experienced an error. Opening up a new window to show you more.
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "csstidy in /Users/kevinkirchner/Library/Application Support/Sublime Text 3/Installed Packages/CSSTidy.sublime-package", line 84, in run
TypeError: can't concat bytes to str
```

**Comment by kevnk** [comment]
I installed the [CSS Format package](https://packagecontrol.io/packages/CSS%20Format) instead which works very well.

**Comment by fitnr** [comment]
This was a string/bytes concatenation issue. Thanks for the tip.
